name: release-typescript-action
description: automate release of typescript-action

inputs:
  major-version:
    description: major version
    required: true
    default: '1'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  dry-run:
    description: dry run flag
    required: true
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
